// PlainOrder — minimal RFC 5545 .ics generator.
//
// Each deadline becomes an all-day VEVENT. Skips deadlines that don't have
// a concrete YYYY-MM-DD date (e.g. "within 30 days of service") because
// we can't put a guess on someone's calendar.

export interface IcsEvent {
  /** YYYY-MM-DD; required to emit a VEVENT. */
  date: string | null;
  what: string;
  notes?: string;
}

const PROD_ID = '-//PlainOrder//EN';
const CAL_NAME = 'PlainOrder deadlines';

export function buildIcs(events: IcsEvent[]): string {
  const dated = events.filter((e) => isYmd(e.date));
  if (!dated.length) return '';

  const now = new Date();
  const stamp = formatUtcStamp(now);

  const vevents = dated
    .map((e, i) => {
      const date = String(e.date).replace(/-/g, '');
      const next = nextDayYmd(String(e.date));
      const uid = `plainorder-${stamp}-${i}@plainorder.dashable.dev`;
      const summary = escapeText(e.what || 'Deadline');
      const desc = escapeText(
        [e.notes, 'Generated by PlainOrder. Verify against the original document.']
          .filter(Boolean)
          .join('\\n\\n'),
      );
      return [
        'BEGIN:VEVENT',
        `UID:${uid}`,
        `DTSTAMP:${stamp}`,
        `DTSTART;VALUE=DATE:${date}`,
        `DTEND;VALUE=DATE:${next}`,
        `SUMMARY:${summary}`,
        `DESCRIPTION:${desc}`,
        'TRANSP:TRANSPARENT',
        'END:VEVENT',
      ].join('\r\n');
    })
    .join('\r\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:${PROD_ID}`,
    `X-WR-CALNAME:${CAL_NAME}`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    vevents,
    'END:VCALENDAR',
    '',
  ].join('\r\n');
}

function isYmd(s: string | null): s is string {
  return typeof s === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(s);
}

function nextDayYmd(ymd: string): string {
  const [y, m, d] = ymd.split('-').map(Number);
  const date = new Date(Date.UTC(y, m - 1, d));
  date.setUTCDate(date.getUTCDate() + 1);
  return [
    date.getUTCFullYear(),
    String(date.getUTCMonth() + 1).padStart(2, '0'),
    String(date.getUTCDate()).padStart(2, '0'),
  ].join('');
}

function formatUtcStamp(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0');
  return (
    date.getUTCFullYear().toString() +
    pad(date.getUTCMonth() + 1) +
    pad(date.getUTCDate()) +
    'T' +
    pad(date.getUTCHours()) +
    pad(date.getUTCMinutes()) +
    pad(date.getUTCSeconds()) +
    'Z'
  );
}

function escapeText(s: string): string {
  return String(s)
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}
